### ISSUE TITLE
Alice does not respond to the command

### ISSUE THREAD

**Issue by Yu20047** [efekt/Alice#12]
The bot does not respond to commands even though it works perfectly on other servers I tried to kick it then add it nothing to do it worked well before but now on a specific server it no longer works

**Comment by Yu20047** [comment]
I also forgot to mention that it hasn't worked for a day.

**Comment by Yu20047** [comment]
> Les bots doivent maintenant utiliser les commandes slash. Actuellement, je n'ai pas beaucoup de temps pour les réécrire. Veuillez utiliser la `@ALICE`mention afin de les utiliser. ( `@ALICE help`, `@ALICE play`etc...)

Thank you for your quick answer but having tried it still does not work and moreover why on this server specifically while on the others I can always use the <play commands?

**Comment by efekt** [comment]
Probably the way Discord is updating things, in waves. Make sure you are mentioning the bot.
On my test server normal commands are no longer working but mentioning works:
![image](https://user-images.githubusercontent.com/1352621/188160295-70ac856b-b59a-432b-b987-285e27617a8c.png)

**Comment by Yu20047** [comment]
thank you once again for your answer I will wait another day to see if it works again because the mentions do not work

**Comment by Yu20047** [comment]
Nice help for my problem

**Comment by TomBit1** [comment]
When can this be expected to be repaired?

**Comment by efekt** [comment]
Since the 1st of September all bots are required to use slash commands,
this is not implemented yet.
Please use mentions instead of the command prefix, for instance: ***@***.***
help", ***@***.*** play"

pt., 2 wrz 2022 o 14:01 Yu20047 ***@***.***> napisał(a):
