### ISSUE TITLE
i can not play music 

### ISSUE THREAD

**Issue by Mateuszek5555** [efekt/Alice#8]
english: i mean i am writning <play and song title alice write it is playing on command <np she is writing that it is playing but i cant hear anything what should i do?

polish: wpiseuje komende <play i tytuł i wszędzie pisze że ta piosenka gra ale nic nie słychać na kanale głosowym da sie to jakoś naprawić?

**Comment by efekt** [comment]
Maybe it's just paused. Type `<play` to unpause the bot.

**Comment by Mateuszek5555** [comment]
omg im dumb xd
